export const surpriseMePrompts = [
  "A dragon made of clouds flying over a serene mountain range",
  "A steampunk robot butler serving tea in a Victorian-era mansion",
  "A futuristic city skyline with floating gardens and waterfalls, at sunset",
  "A vintage postcard of a mermaid sunbathing on a rocky shore",
  "A magical forest where the trees have glowing leaves and luminescent flowers",
  "A cyberpunk detective investigating a crime scene in a neon-lit alley",
  "An enchanted library with books that float and rearrange themselves",
  "A space pirate ship sailing through a galaxy filled with colorful nebulas",
  "A surreal landscape where mountains are made of candy and rivers flow with chocolate",
  "A whimsical illustration of a giant turtle carrying an island on its back",
  "A fantastical underwater city with glowing buildings and marine life",
  "A serene Japanese garden with a bridge over a koi pond at twilight",
  "A time-traveling explorer encountering dinosaurs in a lush prehistoric jungle",
  "A futuristic spacecraft landing on a vibrant alien planet",
  "A dreamlike scene of a giant moon rising over an ancient castle",
  "A cozy treehouse village high up in the branches of giant redwoods",
  "A retro diner on the moon with astronauts enjoying milkshakes",
  "A mystical phoenix rising from the ashes in a burst of flames",
  "A fairy tale castle surrounded by a field of giant, colorful mushrooms",
  "A winter wonderland with ice castles and frosty pine trees",
  "A group of adventurers exploring a hidden temple in the jungle",
  "A playful scene of animals having a tea party in a forest clearing",
  "A high-tech laboratory with robots and futuristic gadgets",
  "A bustling marketplace in an ancient, fantastical city",
  "A serene mountain lake with a crystal-clear reflection of the stars",
  "A vibrant coral reef teeming with colorful fish and sea creatures",
  "A cosmic ballet of planets and stars swirling around a black hole",
  "A whimsical hot air balloon festival in a fantasy world",
  "A gothic cathedral with stained glass windows depicting mythical creatures",
  "A peaceful Zen garden with carefully raked sand and bonsai trees",
  "A lively carnival with fantastical rides and colorful characters",
  "A futuristic monorail gliding through a neon-lit cityscape",
  "A majestic griffin soaring over a medieval kingdom",
  "A cozy cabin in the woods during a gentle snowfall",
  "A bustling steampunk city with airships floating above",
  "A hidden underwater cave filled with glowing crystals",
  "A serene desert oasis with a tranquil pool and palm trees",
  "A vibrant festival of lights in an ancient, mystical city",
  "A futuristic train traveling through a lush, overgrown jungle",
  "A magical bakery with floating pastries and enchanted ingredients",
  "A serene lakeside cabin with a stunning view of the Northern Lights",
  "A mystical forest with trees that glow in the dark",
  "A bustling city street in the rain, with reflections of neon signs",
  "A retrofuturistic space station with sleek design and glowing lights",
  "A hidden library filled with ancient, magical books",
  "A futuristic underwater research facility with panoramic windows",
  "A fantasy village built into the side of a cliff",
  "A tranquil beach with bioluminescent waves at night",
  "A magical carousel with fantastical creatures as mounts",
  "A mysterious figure standing at the entrance to a hidden cave",
];
