export const TEST = 'TEST';
export const GET_USER_BEGIN = 'GET_USER_BEGIN';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL= 'GET_USER_FAIL';
export const LOGOUT_USER='LOGOUT_USER';
export const LOGIN_USER_BEGIN='LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCESS='LOGIN_USER_SUCESS';
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL';
export const SIGNIN_USER_BEGIN='SIGNIN_USER_BEGIN';
export const SIGNIN_USER_SUCESS='SIGNIN_USER_SUCESS';
export const SIGNIN_USER_FAIL='SIGNIN_USER_FAIL';
export const GET_ALL_POST_BEGIN='GET_ALL_POST_BEGIN';
export const GET_ALL_POST_SUCESS='GET_ALL_POST_SUCESS';
export const GET_ALL_POST_FAIL='GET_ALL_POST_FAIL';
export const GET_USER_POST_BEGIN='GET_USER_POST_BEGIN';
export const GET_USER_POST_SUCESS='GET_USER_POST_SUCESS';
export const GET_USER_POST_FAIL='GET_USER_POST_FAIL';
export const  DELETE_USER_POST='DELETE_USER_POST';









